# Generated by Django 2.2.16 on 2020-09-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hhgjhg'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='hhgjhgjhgjhgjhgjhgjhgjhgjhgjhgjhgjhgjhgjhgjhg',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='nbvnbvnbvnbvnv',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customtext',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
