# Generated by Django 2.2.16 on 2020-09-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200919_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='gcgdghg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
